FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY console/nginx.conf /etc/nginx/conf.d/default.conf
COPY console/index.html /usr/share/nginx/html/index.html
RUN chmod 644 /usr/share/nginx/html/index.html
EXPOSE 80
