apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ganji-dac.fullname" . }}-console
  labels:
    {{- include "ganji-dac.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      {{- include "ganji-dac.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: console
  template:
    metadata:
      labels:
        {{- include "ganji-dac.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: console
    spec:
      containers:
        - name: console
          image: {{ include "ganji-dac.image" (dict "global" .Values.global "image" .Values.console.image) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.console.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
