apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ganji-dac.fullname" . }}-secret
  labels:
    {{- include "ganji-dac.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.api.secret.apiKey | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
